### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by nunofgs** [keis/git-fixup#14]
Hi @keis. Thanks for the great script!

Just to let you know, I've submitted a Homebrew [formula](https://github.com/Homebrew/homebrew/pull/37166) for git-fixup :)

Maybe we could add `brew install` instructions to the README once the formula is merged?

**Comment by keis** [comment]
hi @nunofgs. glad you like it :)

Would be happy to add a note in the readme about installing with brew. Please ping when it gets merged and can sort it out.

**Comment by chernjie** [comment]
Hi @keis @nunofgs , I found this script via Homebrew and I thought that it would be a good candidate for [git-extras](https://github.com/tj/git-extras). What do you think?

**Comment by keis** [comment]
I'm not familiar with git-extras and in general I think it makes more sense to keep tools independent. do one thing and do it well.

that being said I don't really mind where the script ends up and if someone wants to include it in a collection of neat git scripts please go ahead.
