### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by jotrk** [keis/git-fixup#21]
Would you mind adding a license for packaging in distributions?
Thank you!

**Comment by keis** [comment]
IANAL but I don't think I can just slap a license on it as there some other contributors and it's not strictly only my copyright anymore. I'll try to read up on what exactly would be required to do that.

@cgiuffr @fixe would you be ok with adding a ISC license?

**Comment by fixe** [comment]
Why not MIT?

**Comment by keis** [comment]
it's functionally the same but it's a bit shorter. one thing speaking for MIT is perhaps that it's more widely  known

**Comment by cgiuffr** [comment]
No objection from my side, either way.

**Comment by fixe** [comment]
@keis: your call :-)

**Comment by jotrk** [comment]
Thank you very much!
Here's a package for Arch Linux: https://aur.archlinux.org/packages/git-fixup-git/

**Comment by keis** [comment]
Cool! What would be the command to install it on arch?

**Comment by jotrk** [comment]
The easiest thing would be to get a pacman wrapper like [yaourt](https://wiki.archlinux.de/title/Yaourt), but if you want to do it manually, you'd have to fetch the [tarball](https://aur.archlinux.org/packages/gi/git-fixup-git/git-fixup-git.tar.gz), unpack it, `cd` into the directory and run `makepkg`. Then you can install the resulting package with `pacman -U`.
