### ISSUE TITLE
passing HEAD as ref doesn't trigger git's autosquashing

### ISSUE THREAD

**Issue by joeshaw** [keis/git-fixup#23]
Running `git fixup HEAD` results in a commit like:

    [master e2baefa] fixup! HEAD

But running `git rebase --interactive HEAD^2` doesn't automatically flag the commit for fixup.

However, `git fixup $(git rev-parse HEAD)` does work.

You're already calling `git rev-parse --verify` on the commit has passed in, how would you feel about passing the results of that to the `git commit` instead of `$1`?

**Comment by joeshaw** [comment]
Actually, maybe the right thing here is instead replace `git rev-parse --verify` and `git commit -m "fixme! $1"` with simply `git commit --fixme=$1`, which has been supported in git for quite a while now.

**Comment by keis** [comment]
hmm yeah "--fixup" has been around for a few years now so that should be fine to use. And it gives a little error message as a bonus if you mess up :)

**Comment by joeshaw** [comment]
The main downside AFAICT is that it seems to always open the editor for editing your commit message.  I can't figure any way to turn that off :(

**Comment by joeshaw** [comment]
Oops, no, that only happens with squash (which is probably what you want in that case).  I'll force-push to the PR to clean things up.

**Comment by keis** [comment]
right. well that kinda make sense. Looks like you can also combine --squash with -m which would be cool to work in somehow. Will have to stew a bit on that though
