### ISSUE TITLE
Zsh completion yields no output

### ISSUE THREAD

**Issue by eigengrau** [keis/git-fixup#35]
I’ve noticed (using 42dc37d) that the Zsh completion widget currently yields no output (Zsh v.5.3.1).

The problem seems to be `lines=(${(f)"$(git fixup)"}) 2>&1 | read err`, which results in `lines` being empty even though `git fixup` produces the expected output. I’m unfamiliar with this form of pipe construction – is it possible that the way Zsh handles this form of pipe changed recently? I recall that the completion widget has been working for me, but I’m not sure whether I was already using 42dc37d when it broke.

**Comment by keis** [comment]
I just tried 42dc37d872fe and ac1df52db6e0, both work for me. I'm however on zsh 5.2 so that is likely it. The widget is a bit of a copy-paste hack so I'll have to read up a bit on what that construct is actually doing.

**Comment by eigengrau** [comment]
I figured the intention was to get only stderr into `err` and otherwise expand stdout linewise into to `lines` array. The 5.3 [changelog](http://zsh.sourceforge.net/releases.html) doesn’t say anything about changes in commandn substitution, though. Speculatively, Zsh bug or some shell option set on my machine might also be the cause.

**Comment by eigengrau** [comment]
Odd. Occasionally it works. However, running this in `zsh --no-rcs` always leaves both `x` and `err` empty.

```
#!/bin/zsh --no-rcs
x=(${(f)"$(echo test)"}) 2>&1 | read err
echo $x
```

**Comment by keis** [comment]
Tried that script in 5.2 and it writes "test"

**Comment by eigengrau** [comment]
Yeah, just ran it on an old machine which had 5.0 installed and it works there, too.

**Comment by eigengrau** [comment]
This probably was introduced into Zsh by 6ce696f35:

```
 39502: Fork for assignment in LHS of pipeline.
    
      foo=bar | stuff
    
    left the value of foo set to bar as we didn't realise we needed to
    fork.
```

Seems to be intentional, then.

**Comment by eigengrau** [comment]
Not as short as before, sadly. There’s another short, ksh-based trick to separate stdout and stderr, but that won’t work in Zsh. This is using fifos explicitly, as described [here](http://stackoverflow.com/questions/11027679/store-capture-stdout-and-stderr-in-different-variables-bash)

**Comment by keis** [comment]
Yeah, that's a lot of code and I don't like the idea of using temporary files. Maybe it would be better to simply rerun when the list is empty with the assumption it's going to produce the same error again.

**Comment by keis** [comment]
it would also be possible to do 

```
lines=(${(f)"$(git fixup 2>&1)"})
if test $? -ne 0; then
  _message $lines
fi
```

**Comment by eigengrau** [comment]
> it would also be possible to do

Right, that’s probably the best approach. Forgot about the exit status.
