### ISSUE TITLE
Brew version out of date

### ISSUE THREAD

**Issue by quintrino** [keis/git-fixup#40]
It appears that installing via brew does not include the latest changes (specifically --commit )

I think it's because brew reads from the latest releases. https://github.com/keis/git-fixup/releases

**Comment by keis** [comment]
Yeah, I forgot to cut a release for that change. Thanks for the reminder :+1:

**Comment by keis** [comment]
Tagged a 1.2.0 release hopefully that gets picked up be brew. let me know if doesn't happen automagically
