### ISSUE TITLE
Customize number of suggestions

### ISSUE THREAD

**Issue by quintrino** [keis/git-fixup#41]
At the moment it only suggests the two most likely commits, I believe powered by the head -n1 in the locate commits command, could this be defaulted to 1 but customisable? 

As I'm using the fzf menu I'd prefer to have a slightly larger menu that I can then review the git show preview of and select which way works for me. 

Thanks for making such a cool tool.

**Comment by keis** [comment]
No, it's actually not limited in the number of suggestions but sometimes the heuristics used don't produce that many results. Did a bit of an explanation over here https://github.com/keis/git-fixup/issues/29#issuecomment-195406062

I've had some ideas for other clever ways of finding the commits like searching the diffs for tokens of the staged content but for the most part it has worked good enough so I haven't bothered.

The menu with the preview changes to usage pattern so maybe it would even make sense to include all the commits of the branch but the suggested ones on top or something like that. I'm still mostly using tab where that was pretty awful but could be worth revisiting. #30 for reference.
