### ISSUE TITLE
git fixup -> "readarray: command not" on macOS Mojave under zsh

### ISSUE THREAD

**Issue by MaxLeb** [keis/git-fixup#44]
I am facing this error on macOS when running git fixup with staged changes.

**Comment by MaxLeb** [comment]
After investigation, bash is too old on macOS.
Installing bash from brew and changing `git-fixup` to point to `/usr/local/bin/bash` it does not throw the error.
However..it does not output anything.

**Comment by keis** [comment]
Thanks for the report @MaxLeb 
It would be nice if the script worked out of the box on macos and IIRC it does except for the newly added "fallback menu". If there is a not too verbose replacement that can be done in that function I would be happy to apply a patch fixing this.

**Comment by glensc** [comment]
with https://github.com/keis/git-fixup/pull/45 merged (released as 1.3.0) and bash from brew installed, it works as expected. zsh is totally irrelevant (or whatever shell is user using).
