### ISSUE TITLE
readarray: command not found on MacOS

### ISSUE THREAD

**Issue by pe** [keis/git-fixup#48]
`-c` doesn't work on MacOS because there is no `readarray`.

```console
$ git-fixup -c
/usr/local/bin/git-fixup: line 73: readarray: command not found
$ readarray
bash: readarray: command not found
```

Versions:
```console
$ brew info git-fixup
git-fixup: stable 1.3.0 (bottled), HEAD
…
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by keis** [comment]
Hey,

that's unfortunate, I see this is from the built in menu so you have a couple of options

- use another menu, `GITFIXUPMENU=fzf git fixup -c` should be a good start but you can provide any executable or function
- use tab completion instead (this is the way I'm using the tool, sadly on for zsh)
- find some way to install a modern bash (sorry, don't use osx so can't help you with that)
- fix `fallback_menu` to not use readarray, PRs are welcome!

**Comment by keis** [comment]
See #45 looks like updating bash should be possible

**Comment by pe** [comment]
Thank you. And sorry for bothering. I did search the issue for the error message, but only open ones.

I've created a #49.

**Comment by keis** [comment]
Thanks for the PR I'll have a look. No bother at all, sorry if I came across as dismissive.

**Comment by pe** [comment]
> sorry if I came across as dismissive.

Not at all!
