### ISSUE TITLE
What is -d '' good for?

### ISSUE THREAD

**Issue by mcepl** [keis/git-fixup#73]
https://github.com/keis/git-fixup/blob/dc8c1657ca0b12885950150ab30cf4f5df693905/git-fixup#L118

Why `-d ''`, according to all I found on the net, this means that the records need to be `\000` separated, which however they are not here. Also, https://github.com/keis/git-fixup/commit/c2264e1c29002a1744fad557661f848af1a6cbe0 makes this line as a translation of `readarray -t options` which doesn’t set `-d` at all.

**Comment by keis** [comment]
readarray by default already reads the entire input with each input line as a element. The `-d ''` makes read behave in the same way.
